Homepage components
dscnitp/ngo-donations-site pull request #12
Opened 2020-10-20 02:06 UTC by rishabhborn2win

This is the book component which contains about the website and about the developer:
![book](https://user-images.githubusercontent.com/55771529/96531169-a3635800-12a6-11eb-8fba-bda9dcdae443.png)

This is the component describing how can you help using this website:
![cause](https://user-images.githubusercontent.com/55771529/96531172-a52d1b80-12a6-11eb-80b8-934eb8448ea4.png)

This is the review section component:
![review](https://user-images.githubusercontent.com/55771529/96531178-a6f6df00-12a6-11eb-932e-b9c57afe1b52.png)

This is the top Stories carousel:
![stories](https://user-images.githubusercontent.com/55771529/96531182-a8c0a280-12a6-11eb-9c95-4a200225e98c.png)

Added all the SS in the PR.

2020-10-20 02:36 UTC, rishabhborn2win commented
This is the updated what do people think section!

![image](https://user-images.githubusercontent.com/55771529/96533171-03f49400-12ab-11eb-8df4-2e540061e79c.png)

2020-10-20 03:47 UTC, divyaprakash-Rx requested changes
@rishabhborn2win Everything seems fine and nice.
Please run 'npm run format' on the code sync the fork with main repo.

2020-10-20 03:47 UTC, divyaprakash-Rx commented on client/public/index.html
> +<!-- Closed Addition -->
@rishabhborn2win please don't edit index.html or add cdns to it. Use npm modules instead.

2020-10-20 06:47 UTC, divyaprakash-Rx requested changes
@rishabhborn2win Everything is fine now.
Just three things:-
- You have one unnecessary package-lock.json in root folder(the folder of which client and server are subfolders), please delete that.
- Transfer all the components file of homepage to src/components/home from src/components.
- Use prettier before merging.

2020-10-20 07:05 UTC, rishabhborn2win commented
@divyaprakash-Rx Have done all the updates which you told.

2020-10-20 07:39 UTC, divyaprakash-Rx approved these changes

2020-10-21 06:00 UTC, divyaprakash-Rx approved these changes

2020-10-21 16:47 UTC, rishabhborn2win commented
The styles have got some errors when it got merged with the master branch.

2020-10-21 16:59 UTC, divyaprakash-Rx commented
> 
> 
> The styles have got some errors when it got merged with the master branch.

It happens because some are overwriting the default css classes of libraries.

2020-10-23 09:22 UTC, closed without merging