updated news as well as book component
dscnitp/ngo-donations-site pull request #28
Opened 2020-10-25 08:54 UTC by rishabhborn2win

now both of this component is responsive in mobile accordingly!

2020-10-25 10:59 UTC, raksh543 requested changes
@rishabhborn2win Please fix the news section width which is changing on clicking on read more.
![image](https://user-images.githubusercontent.com/51185686/97105216-42d97e00-16df-11eb-987e-9ec2fb0bcb3b.png)

![image](https://user-images.githubusercontent.com/51185686/97105222-4a992280-16df-11eb-8e7f-61110b80ff02.png)

2020-10-25 15:10 UTC, rishabhborn2win commented
> @rishabhborn2win Please fix the news section width which is changing on clicking on read more.
> ![image](https://user-images.githubusercontent.com/51185686/97105216-42d97e00-16df-11eb-987e-9ec2fb0bcb3b.png)
> 
> ![image](https://user-images.githubusercontent.com/51185686/97105222-4a992280-16df-11eb-8e7f-61110b80ff02.png)
> 

Ok

2020-10-26 08:01 UTC, rishabhborn2win commented
Completed with all the changes!

2020-10-27 12:08 UTC, raksh543 approved these changes

2020-10-27 12:08 UTC, merged