User-profile frontend
dscnitp/ngo-donations-site pull request #9
Opened 2020-10-19 11:13 UTC by ayeshaqaisar

User-profile Frontend
![Screenshot (1099)](https://user-images.githubusercontent.com/56070872/96443409-2f836a00-122a-11eb-81cf-a01e328d73b5.png)
![Screenshot (1100)](https://user-images.githubusercontent.com/56070872/96443418-327e5a80-122a-11eb-8f55-7a172c8e0768.png)
![Screenshot (1101)](https://user-images.githubusercontent.com/56070872/96443427-34481e00-122a-11eb-84bf-b3b99218d162.png)

2020-10-19 11:30 UTC, Devanshi-123 approved these changes

2020-10-19 11:36 UTC, Devanshi-123 requested changes
1. Make the image section round instead of the square as shown in the design
2. Export this file  user.js and import it in app.js and use that component in app.js

2020-10-19 11:43 UTC, raksh543 commented
@ayeshaqaisar Also please do proper formatting of your files (indentation and remove extra lines)

2020-10-19 12:13 UTC, divyaprakash-Rx requested changes
@ayeshaqaisar As your page contains many small components repeated multiple times, please make their single components and import after that.
e.g. you can create profile-card.js and use it again again passing names and img url as props.

2020-10-19 12:13 UTC, divyaprakash-Rx commented on client/public/index.html
> +<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
@ayeshaqaisar Please remove these and use npm modules instead.

2020-10-19 12:13 UTC, divyaprakash-Rx commented on client/public/index.html
> +  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
@ayeshaqaisar Please remove these and use npm modules instead.

2020-10-21 17:36 UTC, ayeshaqaisar commented
> 1. Make the image section round instead of the square as shown in the design
> 2. Export this file  user.js and import it in app.js and use that component in app.js

![Screenshot (1112)](https://user-images.githubusercontent.com/56070872/96756581-e54ce500-13f1-11eb-9f74-a4a9ebc393a2.png)
Changed the image's shape
and imported user.js in app.js

2020-10-24 09:46 UTC, divyaprakash-Rx requested changes
@ayeshaqaisar  Great Job 🎉!
You have made many of your parts responsive and code structure is also clean now.
But these are some places that requires your attention:-
- [x] The Profile picture keeps on floating and '+' button is not fixed with it. 
One of the fixes for it is wrap both of them inside a div and then use it as a single component(e.g. Profilepic); and then wrap the complete part(Profilepic and name&organization div(class=User-profile-top) together. 

Also, it is of a fixed size due to which it goes out of view box in mobile views.
- [ ] The div inside which there are inputs for name and organization, is of completely fixed size due to which it goes out of viewbox for screen sizes smaller than 800px. 
One of the fixes for this is to make that div of 50vw for screen size greater than 768px and for screen sizes below 768px, make it to 100vw.
- [ ] Please make input box of activity of flexible size. It also goes out of viewbox.

I have added some of screenshots for your reference.

![FireShot Capture 062 - React App - deploy-preview-9--muckin netlify app](https://user-images.githubusercontent.com/55322166/97078707-86fb4e80-160b-11eb-8a99-0382f71ba519.png)
![Screen Shot 2020-10-24 at 15 13 01](https://user-images.githubusercontent.com/55322166/97078715-9084b680-160b-11eb-91a1-8a4ca98086a5.png)
![Screen Shot 2020-10-24 at 15 13 08](https://user-images.githubusercontent.com/55322166/97078716-937fa700-160b-11eb-8bf3-b196e760c479.png)
![Screen Shot 2020-10-24 at 15 15 01](https://user-images.githubusercontent.com/55322166/97078731-b5792980-160b-11eb-874f-54ab118a05b6.png)

2020-10-24 16:06 UTC, divyaprakash-Rx approved these changes
Perfect!✨🎉

2020-10-24 16:11 UTC, Devanshi-123 approved these changes

2020-10-25 11:26 UTC, raksh543 requested changes
@ayeshaqaisar Please solve these alignment issues.
![image](https://user-images.githubusercontent.com/51185686/97105682-d2346080-16e2-11eb-937b-6554ae84bb9d.png)

- Make the edit and bin buttons clickable (cursor: pointer).
- On clicking on +, user should be able to browse image from the device.

2020-10-26 06:11 UTC, ayeshaqaisar commented
> @ayeshaqaisar Please solve these alignment issues.
> ![image](https://user-images.githubusercontent.com/51185686/97105682-d2346080-16e2-11eb-937b-6554ae84bb9d.png)
> 
> * Make the edit and bin buttons clickable (cursor: pointer).
> * On clicking on +, user should be able to browse image from the device.

Done. Please check

2020-10-27 12:21 UTC, raksh543 approved these changes

2020-10-28 14:40 UTC, merged